### ISSUE TITLE
TypeError: Cannot read property 'if' of undefined

### ISSUE THREAD

**Issue by break9** [peterreisz/laravel-elixir-ngtemplatecache#4]
elixir(function(mix) {
    mix
        .ngTemplateCache()
        .less("styles.less")
....................

I am getting the following error:

.../node_modules/laravel-elixir-ngtemplatecache/index.js:6
    gulpIf = elixir.Plugins.if,
                           ^
TypeError: Cannot read property 'if' of undefined
    at Object.<anonymous> (...../node_modules/laravel-elixir-ngtemplatecache/index.js:6:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (........../gulpfile.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by peterreisz** [comment]
You are probably trying to use the version 0.2.0 with laravel elixir version 2.x.
If this isn't true please provide your version number of the this module and the laravel elixir, otherwise please use the version 0.1.0 or upgrade to laravel elixir 3.x.

**Comment by break9** [comment]
That was the issue.

I rolled back to version 0.1.0

-Thank you
